# Generated by Django 5.1.7 on 2025-04-03 07:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0003_rename_name_file_url_alter_file_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fileversion",
            name="file",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="versions",
                to="files.file",
            ),
        ),
    ]
